language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull hashicorp/terraform:0.12.9

script:
  - # https://github.com/hashicorp/terraform/issues/21408
  - echo "provider \"aws\" { region = \"us-east-1\" }" >> provider.tf
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.12.9 init
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.12.9 validate
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.12.9 fmt -write=false -diff=true -check=true
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.12.9 get
